name: Test
run-name: "Test"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      nats_server:
        image: nats:latest
        ports:
          - 4222:4222
          - 8222:8222

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test; CI=1 test:nats
